#!/bin/bash
TMPDIR=/tmp/cse13s
chmod 700 $TMPDIR
pushd $TMPDIR
rm -rf $TMPDIR/scan-build*
for i in *
do
(
  if [ "$1" != "" ] 
  then
     pushd $i/$1 ;
  else
     pushd $i ;
  fi
  if [ -e Makefile ] || [ -e makefile ]
  then
    make clean
  fi
  git pull
  if [ -e Makefile ] || [ -e makefile ]
  then
    #make clean
    scan-build make
    make
  fi
  popd
)
echo $i
done
