== Source Code Version Control

"Dire Straits is a great band. Someone tells you they like 'Brother in Arms' and
immediately you know they're a stupid annoying git."
-- Alexei Sayle

The deliverables for each of your assignments will be maintained through your
`git` repository. We are using GitLab, which is a service coupled with the
version-control capabilities of `git`. `git` allows you to maintain multiple
versions of your source files, also known as version control. Version control is
the practice of tracking and making changes to code, such that in the event of
some accident while coding, it is always possible to restore your code to a
previous state. `git` is used through a set of commands within a repository, a
version-controlled directory that stores your files.

=== Setting Up SSH Keys

You will first need to _clone_ your GitLab repository. It is highly recommended
that you use `git` over SSH rather than HTTP. SSH causes GitLab to use secure
communication between `git` and its servers using SSH keys, and that using the
SSH protocol allows for authentication _without_ the need to enter your username
or password each time.

SSH keys come in _pairs_: a _private_ key and a _public_ key. Data encrypted
with some public key can only be decrypted with the corresponding private key
and vice versa; public key cryptography. To generate an SSH keypair:

[source,bash]
----
$ ssh-keygen
----

The SSH keypair generated by the default prompt answers will be
sufficient for your needs for use with GitLab. Make sure you add the
_public_ key of the generated key pair to GitLab and that it is an
RSA key. To print your public key so that you can copy it to your
clipboard, enter the following:

[source,bash]
----
$ cat ~/.ssh/id_rsa.pub
----

After adding the key, you will be ready to clone your GitLab repository. For
more in-depth instructions on generating and adding SSH keys, as well as other
GitLab basics, please refer to this link:
https://git.ucsc.edu/help/gitlab-basics/README.md[GitLab Basics].

=== Cloning Your Repository

To clone your repository, run the following command, substituting
`<CruzID>` with your CruzID:

[source,bash]
----
$ git clone git@git.ucsc.edu:cse13s/fall2021/<CruzID>.git cse13s
----

You will be prompted for permission to authenticate with the server.
When permitted, the command will clone your repository onto your machine into a
directory named `cse13s` in the current working directory. Use the
`cd` command to enter the `asgn0` directory in your cloned
`cse13s` repository to start your work for assignment 0.

[source,bash]
----
$ cd cse13s/asgn0
----

=== The `.ssh` Directory and File Permissions

We'll take a moment here to discuss the contents of the
`~/.ssh` directory found on macOS and
Unix-based systems footnote:[The `~/.ssh`
directory equivalent on Windows is typically
`C:\Users\<username>\.ssh`. Your coursework,
however, should be done on Ubuntu 20.04.], along with basic file
permissions on Unix. There are two files of note, other than
generated public and private keys:
`~/.ssh/known_hosts` and
`~/.ssh/authorized_keys`.

The `~/.ssh/known\_hosts` file contains the SSH
fingerprints of every remote machine you choose to SSH onto. Whenever
you try to SSH onto a new machine, a prompt will appear asking if you
want to continue connecting, where an affirmative response will cause
the remote machine's SSH fingerprint to be _appended_ to the known
hosts file.

The `~/.ssh/authorized\_keys` file contains the
public keys of all remote clients that are authorized to remotely log
onto the server using SSH authentication, the server in which is the
machine that contains the file of authorized keys. Note that the UCSC Unix
Timeshare __does not__ support SSH authentication.

Each of the aforementioned SSH-related files, including the public and
private keys, require specific _file permissions_. File permissions
on Unix are what allow you as a user to read and modify (write)
files, as well as what prevents others from being able to read and
modify files. File permissions are split into three access groups:

. User -- the owner of the file, typically the user that created
  the file.
. Group -- a specific set of users.
. Other -- anyone who isn't the user or part of the authorized
  group.

These three access groups each have three access modes:

. Read -- the ability to view the contents of a file.
. Write -- the ability to modify or delete the contents of a
  file.
. Execute -- the ability to run a file as a program.

Note that the three access modes were described with files in mind. On Unix,
directories are also considered files, but the access modes do slightly
different things. Read permission for a directory allows permitted users to list
files in the directory with a program such as `ls`. Write permission for a
directory allows permitted users to modify, create, or delete files in the
directory. Lastly, execute permission for a directory allows permitted users to
access files within the directory, as well as make the directory their current
working directory by using a shell builtin such as `cd` or `pushd`.

The granting and removal of file permissions can be done using the
`chmod` utility, typically specifying the desired permissions
with three `octal` digits. Why octal? There are exactly two states that
each permission can be in: read permission is granted, or it isn't. As a
bit, this means either a 0 or 1. Since there are read, write, and
execute permissions, this naturally means latexmath:[2^3 = 8] possible states,
which can be perfectly expressed using one octal digit. Since there are
three different access groups (user, group, and other), three octal
digits are used.

The permissions of your `~/.ssh` directory should
be `700`. The leftmost octal digit signifies user permissions,
the middle octal digit signifies group permissions, and the rightmost
octal digit signifies other permissions. Thus, the permissions on this
directory allows only the user to enter it, as well as read and modify
files. To explicitly set the permissions as `700` using
`chmod`:

[source,bash]
----
$ chmod 700 ~/.ssh
----

Make sure the permissions for the files in your SSH directory are set as
follows:

* `known_hosts` -- `644`
* `authorized_keys` -- `600`
* any private key -- `600`
* any public key -- `644`

You can create as many public and private keys with `ssh-keygen`
as you want, but you really _only need one_.
